; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
;platform = espressif32 @ 6.6.0
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
lib_archive = false
;lib_ldf_mode = deep+
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.f_cpu = 240000000L

; --- MCU Hardware
[master]
upload_speed = 921600
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1  ; Native USB Output
    -D SIMPLEFOC_ESP32_USEMCPWM

[slave]
upload_speed = 921600
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0  ; UART Output
    -D SIMPLEFOC_ESP32_USEMCPWM

; --- MCU Protocols
[mater_ota]
extends = master
upload_protocol = espota
upload_port = 10.134.249.182

[master_usb]
extends = master
upload_protocol = esptool
upload_port = COM[4]

[slave_ota]
extends = slave
upload_protocol = espota
upload_port = 10.134.249.173

; --- Environments
[env:blink]
extends = master_usb
build_src_filter = +<test_master_blink.cpp>

[env:blink_ota]
extends = mater_ota
build_src_filter = +<test_master_blink.cpp>

[env:blink_slave]
extends = slave
build_src_filter = +<blink_slave.cpp>

[env:master_interchip]
extends = master_usb
build_src_filter = +<master_interchip.cpp>

[env:slave_interchip]
extends = slave
build_src_filter = +<slave_interchip.cpp>

[env:ota_test]
extends = slave
build_src_filter = +<ota.cpp>

[env:ota_upload]
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter = +<ota_upload.cpp>

[env:vsense]
extends = master_usb
build_src_filter = +<test_vsense.cpp>

[env:oled_test]
extends = master
build_src_filter = +<test_oled.cpp>
lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9

[env:i2c_scan]
extends = master
build_src_filter = +<i2c_scan.cpp>

[env:IMU]
extends = master
build_src_filter = +<test_imu.cpp>
lib_ldf_mode = deep+
lib_deps = 
    https://github.com/adafruit/Adafruit_LSM6DS.git
    https://github.com/adafruit/Adafruit_Sensor.git
    https://github.com/adafruit/Adafruit_BusIO.git
    Wire
    SPI
    arduino-libraries/Madgwick @ ^1.2.0

[env:u8g2]
extends = master
build_src_filter = +<test_u8g2.cpp>
lib_deps =
    olikraus/U8g2 @ ^2.35.19

[env:encoder_register]
extends = master
build_src_filter = +<test_encoder_register.cpp>
lib_deps =
    SPI

[env:encoder_test_angle]
extends = master
build_src_filter = +<test_encoder_angle.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.4.0
    simplefoc/SimpleFOCDrivers @ ^1.0.7
    SPI

[env:driver_register]
extends = master
build_src_filter = +<driver_register.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.2
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI

[env:driver_PWM]
extends = master
build_src_filter = +<driver_PWM.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.2
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI

[env:driver_SFOC_OpenLoop]
extends = master
build_src_filter = +<driver_SFOC_OpenLoop.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.2
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI

[env:encoder_SFOC]
extends = master_usb
build_src_filter = +<encoder_SFOC.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.2
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI

[env:driver_velocity_ClosedLoop]
extends = master
build_src_filter = +<driver_velocity_ClosedLoop.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.2
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI

[env:debug]
extends = master
build_src_filter = +<debug.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.2
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI

[env:driver_torque_source]
extends = master
build_src_filter = +<driver_torque_source.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.4
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI
    olikraus/U8g2 @ ^2.35.19

[env:driver_torque_static]
extends = master
build_src_filter = +<driver_torque_static.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.2
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI

[env:driver2]
extends = slave
build_src_filter = +<driver2.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.4
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI

[env:driver3]
extends = slave
build_src_filter = +<driver3.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.4
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI

[env:driver_torque_voltage]
extends = master
build_src_filter = +<driver_torque_voltage.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.3.2
    simplefoc/SimpleFOCDrivers @ ^1.0.6
    SPI
    olikraus/U8g2 @ ^2.35.19

[env:LED_smart]
extends = master
build_src_filter = +<LED_smart.cpp>
lib_deps =
    fastled/FastLED @ ^3.6.0

[env:IMU_madgwick]
extends = master
build_src_filter = +<IMU_madgwick.cpp>
lib_ldf_mode = deep+
lib_deps = 
    https://github.com/adafruit/Adafruit_LSM6DS.git
    https://github.com/adafruit/Adafruit_Sensor.git
    https://github.com/adafruit/Adafruit_BusIO.git
    arduino-libraries/Madgwick @ ^1.2.0
    Wire
    SPI

[env:IMU_mahony]
extends = master
build_src_filter = +<IMU_mahony.cpp>
lib_ldf_mode = deep+
lib_deps = 
    https://github.com/adafruit/Adafruit_LSM6DS.git
    https://github.com/adafruit/Adafruit_Sensor.git
    https://github.com/adafruit/Adafruit_BusIO.git
    Wire
    SPI
    arduino-libraries/Madgwick @ ^1.2.0

[env:killswitch]
extends = master
build_src_filter = +<switch.cpp>

[env:brake]
extends = master
build_src_filter = +<brake.cpp>

[env:KV]
extends = master_usb
build_src_filter = +<test_KV.cpp>
lib_deps =
    askuric/Simple FOC @ ^2.4.0
    simplefoc/SimpleFOCDrivers @ ^1.0.7