; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:edgebalance]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip
board = esp32-s3-devkitm-1
framework = arduino
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
monitor_speed = 115200
upload_speed = 921600

; Global libraries that BOTH microcontrollers need
lib_deps = 
    bakercp/PacketSerial @ ^1.4.0
    askuric/Simple FOC @ ^2.4.0

; --- MASTER MCU (Control Brain) ---
[env:master]
extends = env:edgebalance
build_src_filter = -<*> +<master.cpp> +<InterchipComms.cpp>
upload_port = COM4
upload_protocol = esptool
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1  ; Native USB Output

lib_ignore = WebDashboard

; Master needs the motor and sensor libraries
lib_deps =
    ${env:edgebalance.lib_deps}
    https://github.com/adafruit/Adafruit_LSM6DS.git
    https://github.com/adafruit/Adafruit_Sensor.git
    https://github.com/adafruit/Adafruit_BusIO.git


; --- SLAVE MCU (Wi-Fi Dashboard) ---
[env:slave]
extends = env:edgebalance
build_src_filter = -<*> +<slave.cpp> +<InterchipComms.cpp>
upload_port = COM3
upload_protocol = esptool
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0  ; UART Output

; Slave needs the web and JSON libraries
lib_deps =
    ${env:edgebalance.lib_deps}
    mathieucarbou/ESPAsyncWebServer @ ^3.3.23
    bblanchon/ArduinoJson @ ^6.21.3